spring:
  datasource:
    url: jdbc:h2:mem:~/circuitbreaker
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

naver-client-key: xx
naver-client-secret: xx

aladin-client-ttbkey: xx
